# version key removed as it is obsolete in newer Compose versions

services:

  mysql:
    image: mysql:latest
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    # ports:
    #   - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - gibbon-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gibbon-app
    restart: unless-stopped
    env_file: .env
    environment:
      GIBBON_PATH: /var/www/html
    # Port mapping removed; Nginx reverse proxy will expose port 9000
    volumes:
      - ./gibbon-core/:/var/www/html
      - ./data/app_data:/var/www/html/uploads
      - ./data/app_logs:/var/log/php
      - ./data/tmp_sessions:/tmp/sessions
    # depends_on:
    #   mariadb:
    #     condition: service_healthy
    networks:
      - gibbon-network


  # Redis Cache Service (Optional)
  redis:
    image: redis:alpine
    container_name: gibbon-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis_data:/data
    networks:
      - gibbon-network
  nginx:
    image: nginx:alpine
    container_name: gibbon-nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "9000:80"
    volumes:
      - ./gibbon-core/:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - gibbon-network
volumes:
  db_data:
    driver: local
  app_data:
    driver: local
  app_logs:
    driver: local
  redis_data:
    driver: local

networks:
  gibbon-network:
    driver: bridge

